version: '3.8'
services:
  api:
    container_name: meli-middleend
    restart: always
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    # volumes:
    #   - .:/usr/src/app

  db:
    container_name: meli-postgresql
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}

volumes:
  data: {}
